version: "3.9"

services:
  postgresql:
    image: "postgres:15.1"
    restart: always
    environment:
      POSTGRES_PASSWORD: password123 # Does not matter to have this exposed in dev environments
      POSTGRES_DB: waverchat_dev
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/data/postgres

volumes:
  pg_data:
    driver: local